Enumerables
lekegitrepo/advanced-building-blocks-enumerables pull request #2
Opened 2019-09-20 20:05 UTC by lekegitrepo

2019-09-20 20:13 UTC, lekegitrepo commented
I enabled stickler and added the necessary files.

2019-09-21 07:49 UTC, Oghenebrume50 requested changes
Hi @lekegitrepo your approach to the implementation of this is cool :clap: Please see the below things that is needed to be accomplished. You may need to refer to self more to fulfil some of those, kudos on your first attempt :+1:  Please request for a re-review when you are done :pray: 

my_each returns an Enumerator if no block is given
my_each_with_index returns an enumerator if no block is given
my_select returns an enumerator if no block is given
my_all? returns true if the block never returns false or nil
my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
my_none? when no block or argument is given returns true only if none of the collection members is true
my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex
my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
my_count returns the number of items in enum through enumeration
my_count counts the number of items in enum that are equal to item if an argument is given
my_map returns a new array with the results of running block once for every element in enum.
my_map returns an Enumerator if no block is given
my_inject combines all elements of enum by applying a binary operation, specified by a block
my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-09-24 01:15 UTC, bolah2009 requested changes
## Nice job @lekegitrepo  :smile: 

#### Awesome progress... :muscle: All methods are working just fine with only one exception. :clap: 

Please see comment below, fix it and submit another code review request. 

- Update PR Description
   ![update-PR-description](https://user-images.githubusercontent.com/36057474/64303100-8672a500-cf7e-11e9-999c-d23c06358f0e.gif)

#### :recycle:  Make these changes and submit another code review request. :+1: 
#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-24 01:15 UTC, bolah2009 commented on enumerable.rb
> +# puts multiply_els([2, 4, 5])
#### `REQUIRED`

Consider deleting commented out codes. If you need to review a previous version of your code, use git history.

2019-09-24 01:15 UTC, bolah2009 commented on enumerable.rb
> +  def my_count(items = nil)
#### REQUIRED

There is a :bug: with `my_count` method. Please, let's fix this.

```ruby
$ irb
irb(main):001:0> require_relative 'enumerable'
=> true
irb(main):002:0> [1,2,3,4,5].count(3)
=> 1
irb(main):003:0> [1,2,3,4,5].my_count(3)
=> 0
```

2019-09-24 12:42 UTC, bolah2009 approved these changes
## Awesome :clap: 

Good job making all suggested changes. :100: 


### It's a :+1: from me.


#### :heavy_check_mark:  This project is approved.  You can merge to master. :+1: 

As suggested in the previous review, please edit and update this PR description (:point_down:)

![lekepr](https://user-images.githubusercontent.com/36057474/65512406-08e0eb80-ded1-11e9-9522-9f25b2046a83.png)

2019-09-24 15:29 UTC, merged